# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# ================================================================================================
# meta-infra - Optional: Cloud Storage
# ================================================================================================
# Cloud storage sync tools
# Priority: Optional
# ================================================================================================

$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: onedrive
      settings:
        id: Microsoft.OneDrive
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: google_drive
      settings:
        id: Google.GoogleDrive
        source: winget
  configurationVersion: 0.2.0
