# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# ================================================================================================
# meta-infra - Optional: NVIDIA Hardware
# ================================================================================================
# NVIDIA GPU tools
# Priority: Optional (NVIDIA GPU users only)
# WARNING: Only for NVIDIA GeForce/RTX GPUs
# ================================================================================================

$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nvidia_geforce
      settings:
        id: Nvidia.GeForceExperience
        source: winget
  configurationVersion: 0.2.0
