# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# ================================================================================================
# meta-infra - Optional: AMD Hardware
# ================================================================================================
# AMD GPU tools
# Priority: Optional (AMD GPU users only)
# WARNING: Only for AMD Radeon GPUs
# NOTE: AMD drivers are recommended to be downloaded from official website
# ================================================================================================

$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources: []
  configurationVersion: 0.2.0
