# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# ================================================================================================
# meta-infra - Optional: Security
# ================================================================================================
# Security software (alternative to Windows Defender)
# Priority: Optional
# WARNING: This will disable Windows Defender
# ================================================================================================

$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: huorong
      settings:
        id: Huorong.Huorong
        source: winget
  configurationVersion: 0.2.0
