# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# ================================================================================================
# meta-infra - Standard: AI Tools
# ================================================================================================
# AI tools
# Priority: Recommended
# ================================================================================================

$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: cherry_studio
      settings:
        id: kangfenmao.CherryStudio
        source: winget
  configurationVersion: 0.2.0
