# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# ================================================================================================
# meta-infra - Standard: Media
# ================================================================================================
# Media tools (video player, file conversion)
# Priority: Recommended
# ================================================================================================

$schema: https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    # === Video Player ===
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: potplayer
      settings:
        id: Daum.PotPlayer
        source: winget
  configurationVersion: 0.2.0
